use noise::{NoiseFn, Perlin};

use crate::config::WorldConfig;
use crate::sim::cell::Cell;
use crate::sim::genome::GenomeHash;

// ── Tile ────────────────────────────────────────────────────────────

/// A single grid tile. Stores a cell reference and environmental state.
/// `cell_id = 0` means the tile is empty (index 0 is a reserved sentinel).
#[derive(Debug, Clone, Copy)]
pub struct Tile {
    /// Index into the cell pool. 0 = no cell present.
    pub cell_id: u32,
    /// Scavengeable energy from dead cells.
    pub decay_energy: f32,
    /// Signal layer written by cells, decays per tick.
    pub pheromone: f32,
    /// Pollution layer, generated by death clusters.
    pub toxin: f32,
    /// Static temperature set at world init (Perlin noise).
    pub temperature: u8,
    /// Static sunlight derived from Y position (gradient).
    pub sunlight: u8,
}

impl Tile {
    /// Empty tile: no cell, no environmental deposits.
    pub const EMPTY: Self = Self {
        cell_id: 0,
        decay_energy: 0.0,
        pheromone: 0.0,
        toxin: 0.0,
        temperature: 0,
        sunlight: 0,
    };
}

// ── Simulation statistics ───────────────────────────────────────────

#[derive(Debug, Clone, Default)]
pub struct SimStats {
    pub population: u32,
    pub total_energy: f64,
}

// ── WorldSnapshot ───────────────────────────────────────────────────

/// Lightweight projection of the world state for the renderer.
/// Only data the renderer needs is copied — not a full world clone.
#[derive(Debug, Clone)]
pub struct WorldSnapshot {
    pub tick: u64,
    pub cells: Vec<(u16, u16, GenomeHash)>,
    pub decay_map: Vec<f32>,
    pub pheromone_map: Vec<f32>,
    pub toxin_map: Vec<f32>,
    pub stats: SimStats,
}

// ── World ───────────────────────────────────────────────────────────

pub struct World {
    pub width: u32,
    pub height: u32,

    /// Double-buffered tile grids. All reads from `current`, writes to `next`.
    grids: [Vec<Tile>; 2],
    /// Which grid index (0 or 1) is the current readable grid.
    current: usize,

    /// Contiguous cell pool. Index 0 is a reserved sentinel (no cell).
    cells: Vec<Cell>,
    /// Free list: indices of dead/recycled cell slots.
    free_list: Vec<u32>,

    /// Two reusable float buffers for diffusion passes.
    pub diffusion_a: Vec<f32>,
    pub diffusion_b: Vec<f32>,

    /// Thermal vent positions (x coordinates along the bottom edge).
    pub vent_positions: Vec<u32>,

    pub tick: u64,
}

impl World {
    /// Create a new world from config. Initializes sunlight gradient and
    /// temperature map via Perlin noise.
    pub fn new(config: &WorldConfig) -> Self {
        let total = (config.grid_width * config.grid_height) as usize;

        // Start with empty tile grids
        let mut grid_a = vec![Tile::EMPTY; total];
        let grid_b = vec![Tile::EMPTY; total];

        // Initialize static environment layers
        let perlin = Perlin::new(config.seed as u32);

        for y in 0..config.grid_height {
            for x in 0..config.grid_width {
                let idx = (y * config.grid_width + x) as usize;

                // Temperature: Perlin noise
                let nx = x as f64 * config.temperature_noise_scale as f64;
                let ny = y as f64 * config.temperature_noise_scale as f64;
                // Perlin returns [-1, 1], map to [0, 255]
                let noise_val = perlin.get([nx, ny]);
                grid_a[idx].temperature = ((noise_val + 1.0) * 0.5 * 255.0) as u8;
            }
        }

        // Sunlight: computed via Beer-Lambert column scan (dynamic each tick,
        // but we do an initial pass with empty tiles for baseline values)
        recompute_sunlight(
            &mut grid_a,
            config.grid_width,
            config.grid_height,
            config.sunlight_gradient_strength,
        );

        // Place thermal vents evenly along the bottom edge
        let vent_positions = if config.vent_count > 0 {
            let spacing = config.grid_width / config.vent_count;
            (0..config.vent_count)
                .map(|i| spacing / 2 + i * spacing)
                .collect()
        } else {
            Vec::new()
        };

        // Cell pool: index 0 is the reserved sentinel
        let sentinel = Cell::new(
            crate::sim::genome::Genome::new([0u8; crate::sim::genome::GENOME_LEN]),
            0.0,
            (0, 0),
        );
        let cells = vec![sentinel];

        World {
            width: config.grid_width,
            height: config.grid_height,
            grids: [grid_a, grid_b],
            current: 0,
            cells,
            free_list: Vec::new(),
            diffusion_a: vec![0.0; total],
            diffusion_b: vec![0.0; total],
            vent_positions,
            tick: 0,
        }
    }

    // ── Toroidal coordinate helpers ─────────────────────────────────

    /// Wrap arbitrary (possibly negative) coordinates onto the toroidal grid.
    #[inline]
    pub fn wrap(&self, x: i32, y: i32) -> (u16, u16) {
        let wx = (x.rem_euclid(self.width as i32)) as u16;
        let wy = (y.rem_euclid(self.height as i32)) as u16;
        (wx, wy)
    }

    /// Convert (x, y) coordinates to a flat buffer index.
    #[inline]
    pub fn tile_index(&self, x: u16, y: u16) -> usize {
        y as usize * self.width as usize + x as usize
    }

    // ── Cell pool operations ────────────────────────────────────────

    /// Add a cell to the pool. Returns its id (index into the pool).
    /// Reuses dead cell slots from the free list when available.
    pub fn spawn_cell(&mut self, cell: Cell) -> u32 {
        if let Some(id) = self.free_list.pop() {
            self.cells[id as usize] = cell;
            id
        } else {
            let id = self.cells.len() as u32;
            self.cells.push(cell);
            id
        }
    }

    /// Mark a cell as dead and return its slot to the free list.
    pub fn kill_cell(&mut self, id: u32) {
        debug_assert!(id > 0, "cannot kill sentinel cell at index 0");
        self.cells[id as usize].energy = 0.0;
        self.free_list.push(id);
    }

    /// Get an immutable reference to a cell by id.
    #[inline]
    pub fn get_cell(&self, id: u32) -> &Cell {
        &self.cells[id as usize]
    }

    /// Get a mutable reference to a cell by id.
    #[inline]
    pub fn get_cell_mut(&mut self, id: u32) -> &mut Cell {
        &mut self.cells[id as usize]
    }

    // ── Grid read/write (double buffering) ──────────────────────────

    /// Read a tile from the current (readable) grid.
    #[inline]
    pub fn current_tile(&self, x: u16, y: u16) -> &Tile {
        let idx = self.tile_index(x, y);
        &self.grids[self.current][idx]
    }

    /// Get a mutable reference to a tile in the next (writable) grid.
    #[inline]
    pub fn next_tile_mut(&mut self, x: u16, y: u16) -> &mut Tile {
        let idx = self.tile_index(x, y);
        let next = 1 - self.current;
        &mut self.grids[next][idx]
    }

    /// Swap current and next grids. After this, what was "next" becomes
    /// the readable "current".
    pub fn swap_buffers(&mut self) {
        self.current = 1 - self.current;
    }

    /// Reset all tiles in the next (writable) grid to EMPTY, but preserve
    /// temperature from the current grid. (Sunlight is recomputed each tick.)
    pub fn clear_next(&mut self) {
        let next = 1 - self.current;
        let total = (self.width * self.height) as usize;
        for i in 0..total {
            let temperature = self.grids[self.current][i].temperature;
            self.grids[next][i] = Tile::EMPTY;
            self.grids[next][i].temperature = temperature;
        }
    }

    /// Recompute sunlight on the current grid using Beer-Lambert column scan.
    /// Call this each tick after diffusion, before sensing.
    pub fn update_sunlight(&mut self, base_alpha: f32) {
        recompute_sunlight(
            &mut self.grids[self.current],
            self.width,
            self.height,
            base_alpha,
        );
    }

    // ── Spatial query ───────────────────────────────────────────────

    /// Scan the toroidal neighborhood around (cx, cy) within `radius`.
    /// Returns positions and cell ids for all occupied tiles (excluding
    /// the center tile itself).
    pub fn neighbors_in_radius(&self, cx: u16, cy: u16, radius: u16) -> Vec<(u16, u16, u32)> {
        let mut result = Vec::new();
        let r = radius as i32;
        for dy in -r..=r {
            for dx in -r..=r {
                if dx == 0 && dy == 0 {
                    continue;
                }
                let (wx, wy) = self.wrap(cx as i32 + dx, cy as i32 + dy);
                let tile = self.current_tile(wx, wy);
                if tile.cell_id != 0 {
                    result.push((wx, wy, tile.cell_id));
                }
            }
        }
        result
    }

    // ── Snapshot ────────────────────────────────────────────────────

    /// Produce a lightweight snapshot of the current world state for rendering.
    pub fn snapshot(&self) -> WorldSnapshot {
        let total = (self.width * self.height) as usize;

        let mut cells_out = Vec::new();
        let mut decay_map = Vec::with_capacity(total);
        let mut pheromone_map = Vec::with_capacity(total);
        let mut toxin_map = Vec::with_capacity(total);
        let mut total_energy = 0.0_f64;

        for i in 0..total {
            let tile = &self.grids[self.current][i];
            decay_map.push(tile.decay_energy);
            pheromone_map.push(tile.pheromone);
            toxin_map.push(tile.toxin);

            if tile.cell_id != 0 {
                let cell = self.get_cell(tile.cell_id);
                cells_out.push((cell.position.0, cell.position.1, cell.genome.hash()));
                total_energy += cell.energy as f64;
            }
        }

        let population = cells_out.len() as u32;

        WorldSnapshot {
            tick: self.tick,
            cells: cells_out,
            decay_map,
            pheromone_map,
            toxin_map,
            stats: SimStats {
                population,
                total_energy,
            },
        }
    }

    /// Read-only access to the current (readable) grid.
    #[inline]
    pub fn current_grid(&self) -> &[Tile] {
        &self.grids[self.current]
    }

    /// Mutable access to the current grid (for in-place updates like diffusion).
    #[inline]
    pub fn current_grid_mut(&mut self) -> &mut [Tile] {
        &mut self.grids[self.current]
    }

    /// Set the cell_id on a tile in the current grid (used by spawner).
    pub fn set_current_tile_cell_id(&mut self, x: u16, y: u16, cell_id: u32) {
        let idx = self.tile_index(x, y);
        self.grids[self.current][idx].cell_id = cell_id;
    }

    /// Total number of live cells (excluding sentinel).
    pub fn population(&self) -> u32 {
        (self.cells.len() as u32 - 1) - self.free_list.len() as u32
    }
}

// ── Sunlight computation (Beer-Lambert column scan) ─────────────────

/// Recompute sunlight for the entire grid using Beer-Lambert attenuation.
/// For each column, light starts at 255 at the top and is attenuated row
/// by row based on each tile's absorption coefficient (α).
///
/// Called once at init and once per tick (after diffusion, before sensing).
pub fn recompute_sunlight(grid: &mut [Tile], width: u32, height: u32, base_alpha: f32) {
    // Per-row base absorption from water depth alone
    let water_alpha = base_alpha / height as f32;

    for x in 0..width {
        let mut intensity: f32 = 255.0;

        for y in 0..height {
            let idx = (y * width + x) as usize;

            // Write sunlight first (light arriving at this row), then
            // attenuate for the next row based on this tile's absorption.
            grid[idx].sunlight = intensity.clamp(0.0, 255.0) as u8;

            let tile_alpha = tile_absorption(&grid[idx], water_alpha);
            intensity *= (-tile_alpha).exp();
        }
    }
}

fn tile_absorption(tile: &Tile, water_alpha: f32) -> f32 {
    let mut tile_alpha = water_alpha;
    if tile.cell_id != 0 {
        tile_alpha += 0.2;
    }
    tile_alpha += tile.decay_energy * 0.004 + tile.toxin * 0.002 + tile.pheromone * 0.001;
    tile_alpha
}

// ── Tests ───────────────────────────────────────────────────────────
#[cfg(test)]
mod tests {
    use super::*;
    use crate::sim::genome::{GENOME_LEN, Genome};

    fn small_config() -> WorldConfig {
        WorldConfig {
            grid_width: 16,
            grid_height: 16,
            vent_count: 2,
            ..WorldConfig::default()
        }
    }

    fn make_cell_at(x: u16, y: u16) -> Cell {
        Cell::new(Genome::new([0u8; GENOME_LEN]), 50.0, (x, y))
    }

    // ── Tile tests ──────────────────────────────────────────────────

    #[test]
    fn empty_tile_has_no_cell() {
        assert_eq!(Tile::EMPTY.cell_id, 0);
    }

    #[test]
    fn empty_tile_has_zero_environmental_state() {
        let t = Tile::EMPTY;
        assert!((t.decay_energy).abs() < f32::EPSILON);
        assert!((t.pheromone).abs() < f32::EPSILON);
        assert!((t.toxin).abs() < f32::EPSILON);
        assert_eq!(t.temperature, 0);
        assert_eq!(t.sunlight, 0);
    }

    #[test]
    fn tile_is_copy() {
        let a = Tile::EMPTY;
        let b = a;
        assert_eq!(a.cell_id, b.cell_id);
    }

    #[test]
    fn tile_size_reasonable() {
        let size = std::mem::size_of::<Tile>();
        assert!(
            size <= 24,
            "Tile is {size} bytes — expected ≤24 (target ~18)"
        );
    }

    // ── Toroidal wrapping ───────────────────────────────────────────

    #[test]
    fn wrap_normal_coordinates() {
        let w = World::new(&small_config());
        assert_eq!(w.wrap(5, 10), (5, 10));
    }

    #[test]
    fn wrap_negative_x() {
        let w = World::new(&small_config());
        assert_eq!(w.wrap(-1, 0), (15, 0)); // -1 mod 16 = 15
    }

    #[test]
    fn wrap_negative_y() {
        let w = World::new(&small_config());
        assert_eq!(w.wrap(0, -1), (0, 15));
    }

    #[test]
    fn wrap_overflow_x() {
        let w = World::new(&small_config());
        assert_eq!(w.wrap(16, 0), (0, 0)); // 16 mod 16 = 0
    }

    #[test]
    fn wrap_overflow_y() {
        let w = World::new(&small_config());
        assert_eq!(w.wrap(0, 17), (0, 1)); // 17 mod 16 = 1
    }

    #[test]
    fn wrap_large_negative() {
        let w = World::new(&small_config());
        assert_eq!(w.wrap(-33, -33), (15, 15)); // -33 mod 16 = 15
    }

    #[test]
    fn tile_index_matches_row_major() {
        let w = World::new(&small_config());
        assert_eq!(w.tile_index(0, 0), 0);
        assert_eq!(w.tile_index(1, 0), 1);
        assert_eq!(w.tile_index(0, 1), 16); // second row
        assert_eq!(w.tile_index(15, 15), 255); // last tile
    }

    // ── World init ──────────────────────────────────────────────────

    #[test]
    fn world_grid_dimensions() {
        let w = World::new(&small_config());
        assert_eq!(w.width, 16);
        assert_eq!(w.height, 16);
        assert_eq!(w.grids[0].len(), 256);
        assert_eq!(w.grids[1].len(), 256);
    }

    #[test]
    fn sunlight_gradient_top_brighter_than_bottom() {
        let w = World::new(&small_config());
        let top_sunlight = w.current_tile(0, 0).sunlight;
        let bottom_sunlight = w.current_tile(0, 15).sunlight;
        assert!(
            top_sunlight > bottom_sunlight,
            "top ({top_sunlight}) should be brighter than bottom ({bottom_sunlight})"
        );
    }

    #[test]
    fn sunlight_top_row_is_brightest() {
        let w = World::new(&small_config());
        let top = w.current_tile(0, 0).sunlight;
        // Top row receives light before any absorption, should be near max
        assert!(top >= 250, "top row should be near-max sunlight, got {top}");
    }

    #[test]
    fn sunlight_monotonically_decreases_with_depth() {
        let w = World::new(&small_config());
        for y in 1..16u16 {
            let above = w.current_tile(0, y - 1).sunlight;
            let here = w.current_tile(0, y).sunlight;
            assert!(
                here <= above,
                "row {y} ({here}) should not be brighter than row {} ({above})",
                y - 1
            );
        }
    }

    #[test]
    fn sunlight_affected_by_tile_contents() {
        let config = small_config();
        let mut w = World::new(&config);
        // Record baseline sunlight at bottom
        let baseline = w.current_tile(0, 15).sunlight;

        // Add toxin to several tiles in column 0
        for y in 0..8u32 {
            let idx = (y * config.grid_width) as usize;
            w.grids[w.current][idx].toxin = 50.0;
        }
        w.update_sunlight(config.sunlight_gradient_strength);

        let after_toxin = w.current_tile(0, 15).sunlight;
        assert!(
            after_toxin < baseline,
            "toxin should reduce sunlight: baseline={baseline}, after={after_toxin}"
        );
    }

    #[test]
    fn vent_positions_count() {
        let w = World::new(&small_config());
        assert_eq!(w.vent_positions.len(), 2);
    }

    // ── Cell pool ───────────────────────────────────────────────────

    #[test]
    fn spawn_returns_nonzero_id() {
        let mut w = World::new(&small_config());
        let id = w.spawn_cell(make_cell_at(1, 1));
        assert!(id > 0, "id 0 is reserved sentinel");
    }

    #[test]
    fn spawn_and_retrieve() {
        let mut w = World::new(&small_config());
        let id = w.spawn_cell(make_cell_at(3, 7));
        let cell = w.get_cell(id);
        assert_eq!(cell.position, (3, 7));
        assert!((cell.energy - 50.0).abs() < f32::EPSILON);
    }

    #[test]
    fn kill_and_reuse_slot() {
        let mut w = World::new(&small_config());
        let id1 = w.spawn_cell(make_cell_at(0, 0));
        w.kill_cell(id1);
        let id2 = w.spawn_cell(make_cell_at(5, 5));
        assert_eq!(id2, id1, "should reuse the freed slot");
        assert_eq!(w.get_cell(id2).position, (5, 5));
    }

    #[test]
    fn get_cell_mut_modifies_in_place() {
        let mut w = World::new(&small_config());
        let id = w.spawn_cell(make_cell_at(0, 0));
        w.get_cell_mut(id).energy = 999.0;
        assert!((w.get_cell(id).energy - 999.0).abs() < f32::EPSILON);
    }

    #[test]
    fn population_tracks_live_cells() {
        let mut w = World::new(&small_config());
        assert_eq!(w.population(), 0);
        let id1 = w.spawn_cell(make_cell_at(0, 0));
        let _id2 = w.spawn_cell(make_cell_at(1, 1));
        assert_eq!(w.population(), 2);
        w.kill_cell(id1);
        assert_eq!(w.population(), 1);
    }

    // ── Double buffering ────────────────────────────────────────────

    #[test]
    fn write_next_then_swap_reads_from_current() {
        let mut w = World::new(&small_config());
        // Write to next grid
        w.next_tile_mut(3, 3).decay_energy = 42.0;
        // Before swap: current grid should still be empty
        assert!((w.current_tile(3, 3).decay_energy).abs() < f32::EPSILON);
        // After swap: the written data is now in current
        w.swap_buffers();
        assert!((w.current_tile(3, 3).decay_energy - 42.0).abs() < f32::EPSILON);
    }

    #[test]
    fn clear_next_preserves_temperature() {
        let mut w = World::new(&small_config());
        let original_temp = w.current_tile(0, 0).temperature;
        w.clear_next();
        w.swap_buffers();
        assert_eq!(w.current_tile(0, 0).temperature, original_temp);
    }

    #[test]
    fn clear_next_resets_dynamic_state() {
        let mut w = World::new(&small_config());
        w.next_tile_mut(5, 5).decay_energy = 100.0;
        w.next_tile_mut(5, 5).cell_id = 42;
        w.clear_next(); // should wipe the dynamic state we just wrote
        w.swap_buffers();
        assert!((w.current_tile(5, 5).decay_energy).abs() < f32::EPSILON);
        assert_eq!(w.current_tile(5, 5).cell_id, 0);
    }

    // ── Spatial query ───────────────────────────────────────────────

    #[test]
    fn neighbors_radius_zero_returns_nothing() {
        let w = World::new(&small_config());
        let result = w.neighbors_in_radius(5, 5, 0);
        assert!(result.is_empty());
    }

    #[test]
    fn neighbors_finds_adjacent_cell() {
        let mut w = World::new(&small_config());
        let id = w.spawn_cell(make_cell_at(6, 5));
        // Place the cell on the current grid
        let idx = w.tile_index(6, 5);
        w.grids[w.current][idx].cell_id = id;

        let result = w.neighbors_in_radius(5, 5, 1);
        assert_eq!(result.len(), 1);
        assert_eq!(result[0], (6, 5, id));
    }

    #[test]
    fn neighbors_wraps_at_edge() {
        let mut w = World::new(&small_config());
        // Place a cell at (15, 0) — right edge
        let id = w.spawn_cell(make_cell_at(15, 0));
        let idx = w.tile_index(15, 0);
        w.grids[w.current][idx].cell_id = id;

        // Search from (0, 0) with radius 1 — should wrap and find (15, 0)
        let result = w.neighbors_in_radius(0, 0, 1);
        assert!(
            result.iter().any(|&(x, y, _)| x == 15 && y == 0),
            "should find cell at (15,0) via toroidal wrap"
        );
    }

    #[test]
    fn neighbors_radius_3_covers_expected_area() {
        let w = World::new(&small_config());
        // No cells placed, but verify the scan covers the right number of tiles
        // Radius 3 = 7x7 grid minus center = 48 tiles scanned
        let result = w.neighbors_in_radius(8, 8, 3);
        assert!(result.is_empty()); // no cells, but no crash
    }

    // ── Snapshot ────────────────────────────────────────────────────

    #[test]
    fn snapshot_reflects_current_state() {
        let mut w = World::new(&small_config());
        let id = w.spawn_cell(make_cell_at(2, 3));
        let idx = w.tile_index(2, 3);
        w.grids[w.current][idx].cell_id = id;
        w.grids[w.current][idx].decay_energy = 7.5;
        w.tick = 42;

        let snap = w.snapshot();
        assert_eq!(snap.tick, 42);
        assert_eq!(snap.cells.len(), 1);
        assert_eq!(snap.cells[0].0, 2);
        assert_eq!(snap.cells[0].1, 3);
        assert_eq!(snap.stats.population, 1);
        assert!((snap.decay_map[idx] - 7.5).abs() < f32::EPSILON);
    }
}
