// @veridikt
// kind: module
// name: World
// purpose: "Grid + cell-pool substrate: double-buffered tiles, the cell pool with its free list, environment layers, and toroidal spatial queries"
// owner: "primordium-maintainers"
// because: "Cells live in a contiguous Vec indexed by tile cell_id rather than embedded in tiles, because most tiles are empty and a dense vec is cache-friendly for the per-tick loop (docs/architecture.md)"
use noise::{NoiseFn, Perlin};

use crate::config::WorldConfig;
use crate::sim::cell::Cell;
use crate::sim::genome::{DecodedGenes, GenomeHash};
use crate::sim::stats::{CellRecord, TickStats};

// ── Tile ────────────────────────────────────────────────────────────

/// A single grid tile. Stores a cell reference and environmental state.
/// `cell_id = 0` means the tile is empty (index 0 is a reserved sentinel).
#[derive(Debug, Clone, Copy)]
pub struct Tile {
    /// Index into the cell pool. 0 = no cell present.
    pub cell_id: u32,
    /// Scavengeable energy from dead cells.
    pub decay_energy: f32,
    /// Per-tick fraction of `decay_energy` that fades away here.
    ///
    /// `docs/spec.md` gene 30, `decay_rate`: "how long the cell's corpse
    /// persists as scavengeable decay matter". The rate therefore belongs to
    /// the corpse, not to the world, so it is carried on the tile and mixed
    /// in proportion to the energy each new deposit brings.
    pub decay_fade: f32,
    /// Signal layer written by cells, decays per tick.
    pub pheromone: f32,
    /// Pollution layer, generated by death clusters.
    pub toxin: f32,
    /// Static temperature set at world init (Perlin noise).
    pub temperature: u8,
    /// Static sunlight derived from Y position (gradient).
    pub sunlight: u8,
}

impl Tile {
    /// Empty tile: no cell, no environmental deposits.
    pub const EMPTY: Self = Self {
        cell_id: 0,
        decay_energy: 0.0,
        decay_fade: 0.0,
        pheromone: 0.0,
        toxin: 0.0,
        temperature: 0,
        sunlight: 0,
    };
}

// ── Simulation statistics ───────────────────────────────────────────

#[derive(Debug, Clone, Default)]
pub struct SimStats {
    pub population: u32,
    pub total_energy: f64,
}

// ── CellView ────────────────────────────────────────────────────────

/// Which energy channel a cell is built around, from its decoded genes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Strategy {
    Photosynthesis,
    Thermosynthesis,
    Scavenging,
    Predation,
    /// No acquisition gene is meaningfully expressed.
    None,
}

/// Everything the renderer needs about one cell.
///
/// The snapshot used to carry `(x, y, GenomeHash)` and nothing else, so no
/// view could show a phase, a strategy or a starving cell — which is why
/// "phases aren't visible" was impossible to answer from the window.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct CellView {
    pub x: u16,
    pub y: u16,
    pub genome: GenomeHash,
    /// Dominant acquisition strategy.
    pub strategy: Strategy,
    /// How dominant that strategy is over the runner-up, 0.0–1.0.
    pub specialization: f32,
    /// Energy as a share of the cell's own storage cap, 0.0–1.0.
    pub energy_fraction: f32,
    /// Age as a share of the cell's own lifespan, 0.0–1.0.
    pub age_fraction: f32,
    /// Active phase slot: 0 = default, 1–3 = phase table slots.
    pub active_phase: u8,
}

// ── WorldSnapshot ───────────────────────────────────────────────────

/// Lightweight projection of the world state for the renderer.
/// Only data the renderer needs is copied — not a full world clone.
#[derive(Debug, Clone)]
pub struct WorldSnapshot {
    pub tick: u64,
    pub cells: Vec<CellView>,
    pub decay_map: Vec<f32>,
    pub pheromone_map: Vec<f32>,
    pub toxin_map: Vec<f32>,
    pub stats: SimStats,
}

// ── World ───────────────────────────────────────────────────────────

pub struct World {
    pub width: u32,
    pub height: u32,

    /// Double-buffered tile grids. All reads from `current`, writes to `next`.
    grids: [Vec<Tile>; 2],
    /// Which grid index (0 or 1) is the current readable grid.
    current: usize,

    /// Contiguous cell pool. Index 0 is a reserved sentinel (no cell).
    cells: Vec<Cell>,
    /// Free list: indices of dead/recycled cell slots.
    free_list: Vec<u32>,

    /// Two reusable float buffers for diffusion passes.
    pub diffusion_a: Vec<f32>,
    pub diffusion_b: Vec<f32>,

    /// Thermal vent positions (x coordinates along the bottom edge).
    pub vent_positions: Vec<u32>,

    pub tick: u64,

    /// Per-cell bookkeeping, indexed like `cells` (slot 0 is the sentinel's).
    /// Nothing in the simulation reads it; see `sim::stats`.
    records: Vec<CellRecord>,
    /// Last founder lineage id handed out by `new_lineage`.
    last_lineage: u32,
    /// What happened during the tick in progress, or the last one completed.
    pub stats: TickStats,
}

impl World {
    /// Create a new world from config. Initializes sunlight gradient and
    /// temperature map via Perlin noise.

    // @veridikt
    // purpose: "Build the initial world: empty double buffer, Perlin temperature map, baseline sunlight, evenly-spaced vents, and the sentinel cell at pool index 0"
    // because: "Index 0 of the cell pool is a reserved sentinel so that tile.cell_id == 0 can mean 'empty' everywhere without a separate occupancy flag"
    pub fn new(config: &WorldConfig) -> Self {
        let total = (config.grid_width * config.grid_height) as usize;

        // Start with empty tile grids
        let mut grid_a = vec![Tile::EMPTY; total];
        let grid_b = vec![Tile::EMPTY; total];

        // Initialize static environment layers
        let perlin = Perlin::new(config.seed as u32);

        for y in 0..config.grid_height {
            for x in 0..config.grid_width {
                let idx = (y * config.grid_width + x) as usize;

                // Temperature: Perlin noise
                let nx = x as f64 * config.temperature_noise_scale as f64;
                let ny = y as f64 * config.temperature_noise_scale as f64;
                // Perlin returns [-1, 1], map to [0, 255]
                let noise_val = perlin.get([nx, ny]);
                grid_a[idx].temperature = ((noise_val + 1.0) * 0.5 * 255.0) as u8;

                // Pre-existing detritus, so the scavenger niche exists from
                // tick 0 rather than only after the first generation dies.
                grid_a[idx].decay_energy = config.initial_decay_matter;
                grid_a[idx].decay_fade = config.decay_rate;
            }
        }

        // Sunlight: computed via Beer-Lambert column scan (dynamic each tick,
        // but we do an initial pass with empty tiles for baseline values)
        recompute_sunlight(
            &mut grid_a,
            config.grid_width,
            config.grid_height,
            config.sunlight_gradient_strength,
            config.cell_light_absorption,
        );

        // Place thermal vents evenly along the bottom edge
        let vent_positions = match config.grid_width.checked_div(config.vent_count) {
            Some(spacing) => (0..config.vent_count)
                .map(|i| spacing / 2 + i * spacing)
                .collect(),
            None => Vec::new(),
        };

        // Cell pool: index 0 is the reserved sentinel
        let sentinel = Cell::new(
            crate::sim::genome::Genome::new([0u8; crate::sim::genome::GENOME_LEN]),
            0.0,
            (0, 0),
        );
        let cells = vec![sentinel];
        let records = vec![CellRecord::default()];

        World {
            width: config.grid_width,
            height: config.grid_height,
            grids: [grid_a, grid_b],
            current: 0,
            cells,
            free_list: Vec::new(),
            diffusion_a: vec![0.0; total],
            diffusion_b: vec![0.0; total],
            vent_positions,
            tick: 0,
            records,
            last_lineage: 0,
            stats: TickStats::default(),
        }
    }

    // ── Toroidal coordinate helpers ─────────────────────────────────

    /// Wrap arbitrary (possibly negative) coordinates onto the toroidal grid.
    #[inline]
    pub fn wrap(&self, x: i32, y: i32) -> (u16, u16) {
        let wx = (x.rem_euclid(self.width as i32)) as u16;
        let wy = (y.rem_euclid(self.height as i32)) as u16;
        (wx, wy)
    }

    /// Convert (x, y) coordinates to a flat buffer index.
    #[inline]
    pub fn tile_index(&self, x: u16, y: u16) -> usize {
        y as usize * self.width as usize + x as usize
    }

    /// Every cell placed on the next grid, as `(cell_id, tile_index)`, in
    /// tile order.
    ///
    /// Identical in set and order to scanning the whole next grid for
    /// non-empty tiles, but costs a pass over the cell pool instead of all
    /// `width * height` tiles — the scan was a fixed cost paid every tick
    /// whether 18 cells were alive or 5000. A pool slot is on the next grid
    /// exactly when the tile at its position holds its id: `prepare_next`
    /// clears every id in next, so a freed slot is never there, and a dead-
    /// this-tick cell (energy <= 0, not yet freed) still is. Sorting by tile
    /// index keeps the order the grid scan had, which matters: cleanup frees
    /// dead slots in this order, and the free list decides which ids later
    /// births reuse.

    // @veridikt
    // purpose: "List the cells on the next grid in tile order without scanning every tile"
    // because: "Energy and cleanup used to walk all 262 144 tiles per tick to find a few hundred cells; tile order is preserved because it feeds the free list and so the whole trajectory"
    pub fn placed_in_next(&self) -> Vec<(u32, usize)> {
        let width = self.width as usize;
        let mut placed: Vec<(u32, usize)> = (1..self.cells.len() as u32)
            .filter_map(|id| {
                let (x, y) = self.cells[id as usize].position;
                (self.next_tile(x, y).cell_id == id).then(|| (id, y as usize * width + x as usize))
            })
            .collect();
        placed.sort_unstable_by_key(|&(_, idx)| idx);
        placed
    }

    // ── Thermal vents ───────────────────────────────────────────────

    /// Is `(x, y)` within `radius` of a thermal vent?
    ///
    /// X is toroidal — the vents sit on a ring along the bottom edge — but
    /// **Y is not**. The zone reaches `radius` rows up from the bottom row
    /// and no further. Wrapping it in Y put vent energy into rows 0..radius,
    /// which `docs/spec.md` (Environment / vertical resource axis) defines
    /// as "Top zone: high sunlight, no vents", and it is also where the
    /// light column starts, so photosynthesizers standing in the brightest
    /// rows were diluting every vent's output without drawing on it.

    // @veridikt
    // purpose: "Single definition of which tiles a thermal vent reaches: toroidal in x along the bottom edge, bounded in y"
    // because: "Vent income and vent food-sensing must agree on the zone, and the zone must not wrap into the photic rows — sunlight does not wrap either, since the Beer-Lambert column restarts at y = 0"
    pub fn is_in_vent_zone(&self, x: u16, y: u16, radius: u32) -> bool {
        let bottom = self.height as i32 - 1;
        if (bottom - y as i32) > radius as i32 || y as i32 > bottom {
            return false;
        }
        self.vent_positions.iter().any(|&vx| {
            let d = (x as i32 - vx as i32).abs();
            d.min(self.width as i32 - d) <= radius as i32
        })
    }

    // ── Cell pool operations ────────────────────────────────────────

    /// Add a cell to the pool. Returns its id (index into the pool).
    /// Reuses dead cell slots from the free list when available.

    // @veridikt
    // purpose: "Allocate a cell id for a new cell, reusing a freed slot before growing the pool (writes the cell pool and consumes from the free list)"
    // because: "The slot's record is reset with it, so a recycled id never inherits a dead cell's lineage or income; callers tag lineage afterwards"
    pub fn spawn_cell(&mut self, cell: Cell) -> u32 {
        if let Some(id) = self.free_list.pop() {
            self.cells[id as usize] = cell;
            self.records[id as usize] = CellRecord::default();
            id
        } else {
            let id = self.cells.len() as u32;
            self.cells.push(cell);
            self.records.push(CellRecord::default());
            id
        }
    }

    /// Bookkeeping for a cell: lineage, lifetime income, cause of death.
    #[inline]
    pub fn record(&self, id: u32) -> &CellRecord {
        &self.records[id as usize]
    }

    #[inline]
    pub fn record_mut(&mut self, id: u32) -> &mut CellRecord {
        &mut self.records[id as usize]
    }

    /// A fresh founder lineage id (1, 2, 3, ...). Ids are handed out in
    /// seeding order and never reused.
    pub fn new_lineage(&mut self) -> u32 {
        self.last_lineage += 1;
        self.last_lineage
    }

    /// Mark a cell as dead and return its slot to the free list.

    // @veridikt
    // purpose: "Retire a cell: zero its energy and return its pool slot to the free list for reuse"
    // assumes: "id > 0 — the sentinel slot at index 0 is never killed (debug-asserted)"
    pub fn kill_cell(&mut self, id: u32) {
        debug_assert!(id > 0, "cannot kill sentinel cell at index 0");
        self.cells[id as usize].energy = 0.0;
        self.free_list.push(id);
    }

    /// Lay `amount` of decay matter on a tile of the next grid, fading at
    /// `fade` per tick. Where the tile already holds matter the two fade
    /// rates are blended by how much each brought, so a body's own
    /// `decay_rate` gene travels with what it left (`docs/spec.md` gene 30).

    // @veridikt
    // purpose: "The one write path for decay matter a dying cell leaves on its tile: add it to the next grid and blend the tile's fade rate by amount"
    // because: "Corpses, the uneaten part of a kill and an old cell's remaining energy all land as the same kind of matter; one helper keeps the fade blending identical for all three"
    pub fn deposit_decay(&mut self, idx: usize, amount: f32, fade: f32) {
        let next = 1 - self.current;
        let tile = &mut self.grids[next][idx];
        let total = tile.decay_energy + amount;
        if total > 0.0 {
            tile.decay_fade = (tile.decay_energy * tile.decay_fade + amount * fade) / total;
        }
        tile.decay_energy += amount;
    }

    /// Get an immutable reference to a cell by id.
    #[inline]
    pub fn get_cell(&self, id: u32) -> &Cell {
        &self.cells[id as usize]
    }

    /// Get a mutable reference to a cell by id.
    #[inline]
    pub fn get_cell_mut(&mut self, id: u32) -> &mut Cell {
        &mut self.cells[id as usize]
    }

    // ── Grid read/write (double buffering) ──────────────────────────

    /// Read a tile from the current (readable) grid.
    #[inline]
    pub fn current_tile(&self, x: u16, y: u16) -> &Tile {
        let idx = self.tile_index(x, y);
        &self.grids[self.current][idx]
    }

    /// Read a tile from the next (writable) grid without mutating.
    #[inline]
    pub fn next_tile(&self, x: u16, y: u16) -> &Tile {
        let idx = self.tile_index(x, y);
        let next = 1 - self.current;
        &self.grids[next][idx]
    }

    /// Get a mutable reference to a tile in the next (writable) grid.
    #[inline]
    pub fn next_tile_mut(&mut self, x: u16, y: u16) -> &mut Tile {
        let idx = self.tile_index(x, y);
        let next = 1 - self.current;
        &mut self.grids[next][idx]
    }

    /// Swap current and next grids. After this, what was "next" becomes
    /// the readable "current".

    // @veridikt
    // purpose: "Publish a tick's writes by flipping which of the two grid buffers is readable"
    // because: "Atomic buffer swap is what makes simultaneous resolution deterministic — all cells decided against one frozen `current`, and the swap commits the `next` they wrote"
    pub fn swap_buffers(&mut self) {
        self.current = 1 - self.current;
    }

    /// Seed the next (writable) grid from the current one: every
    /// environment field (decay, pheromone, toxin, temperature, sunlight)
    /// is carried over and `cell_id` is cleared so action resolution can
    /// place cells from scratch. Call once per tick after diffusion and the
    /// sunlight recompute, before action resolution.

    // @veridikt
    // purpose: "Copy the current grid's environment fields into next with every cell_id cleared, so the energy and cleanup phases (which read and write next) see this tick's sunlight, decay, toxin and pheromone"
    // because: "Energy income and decay consumption read the next grid; wiping next to EMPTY dropped sunlight/decay/toxin/pheromone at every swap, so photosynthesis and scavenging paid nothing and accumulated fields vanished"
    // assumes: "Called after diffusion and update_sunlight have finished mutating the current grid, and before anything is placed into next"
    pub fn prepare_next(&mut self) {
        let [a, b] = &mut self.grids;
        let (cur, next) = if self.current == 0 {
            (&*a, b)
        } else {
            (&*b, a)
        };
        for (n, c) in next.iter_mut().zip(cur.iter()) {
            *n = Tile { cell_id: 0, ..*c };
        }
    }

    /// Recompute sunlight on the current grid using Beer-Lambert column scan.
    /// Call this each tick after diffusion, before sensing. `cell_alpha` is
    /// what one occupied tile adds to the column's absorption.
    pub fn update_sunlight(&mut self, base_alpha: f32, cell_alpha: f32) {
        recompute_sunlight(
            &mut self.grids[self.current],
            self.width,
            self.height,
            base_alpha,
            cell_alpha,
        );
    }

    // ── Spatial query ───────────────────────────────────────────────

    /// Scan the toroidal neighborhood around (cx, cy) within `radius`.
    /// Returns positions and cell ids for all occupied tiles (excluding
    /// the center tile itself).

    // @veridikt
    // purpose: "Spatial query backing sensing: list occupied tiles around a point with toroidal wrap, reading the current grid"
    pub fn neighbors_in_radius(&self, cx: u16, cy: u16, radius: u16) -> Vec<(u16, u16, u32)> {
        let mut result = Vec::new();
        let r = radius as i32;
        for dy in -r..=r {
            for dx in -r..=r {
                if dx == 0 && dy == 0 {
                    continue;
                }
                let (wx, wy) = self.wrap(cx as i32 + dx, cy as i32 + dy);
                let tile = self.current_tile(wx, wy);
                if tile.cell_id != 0 {
                    result.push((wx, wy, tile.cell_id));
                }
            }
        }
        result
    }

    // ── Snapshot ────────────────────────────────────────────────────

    /// Produce a lightweight snapshot of the current world state for rendering.

    // @veridikt
    // purpose: "Copy only what the renderer needs (cell positions+hashes, field maps, stats) out of the live world"
    // because: "The sim thread hands this to the render thread; copying a minimal projection avoids sharing or cloning the whole World across the thread boundary (docs/architecture.md threading model)"
    pub fn snapshot(&self, config: &WorldConfig) -> WorldSnapshot {
        let total = (self.width * self.height) as usize;

        let mut cells_out = Vec::new();
        let mut decay_map = Vec::with_capacity(total);
        let mut pheromone_map = Vec::with_capacity(total);
        let mut toxin_map = Vec::with_capacity(total);
        let mut total_energy = 0.0_f64;

        for i in 0..total {
            let tile = &self.grids[self.current][i];
            decay_map.push(tile.decay_energy);
            pheromone_map.push(tile.pheromone);
            toxin_map.push(tile.toxin);

            if tile.cell_id != 0 {
                let cell = self.get_cell(tile.cell_id);
                cells_out.push(cell_view(cell, config));
                total_energy += cell.energy as f64;
            }
        }

        let population = cells_out.len() as u32;

        WorldSnapshot {
            tick: self.tick,
            cells: cells_out,
            decay_map,
            pheromone_map,
            toxin_map,
            stats: SimStats {
                population,
                total_energy,
            },
        }
    }

    /// Read-only access to the current (readable) grid.
    #[inline]
    pub fn current_grid(&self) -> &[Tile] {
        &self.grids[self.current]
    }

    /// Mutable access to the current grid (for in-place updates like diffusion).
    #[inline]
    pub fn current_grid_mut(&mut self) -> &mut [Tile] {
        &mut self.grids[self.current]
    }

    /// Read-only access to the next (writable) grid.
    #[inline]
    pub fn next_grid(&self) -> &[Tile] {
        let next = 1 - self.current;
        &self.grids[next]
    }

    /// Mutable access to the next (writable) grid.
    #[inline]
    pub fn next_grid_mut(&mut self) -> &mut [Tile] {
        let next = 1 - self.current;
        &mut self.grids[next]
    }

    /// Return IDs of all live cells (energy > 0, excluding sentinel at index 0).
    pub fn cell_ids(&self) -> Vec<u32> {
        // Liveness alone is the test: `kill_cell` zeroes energy before
        // pushing a slot to the free list, so a freed slot is never alive.
        // Scanning the free list per slot made this O(pool x free_list) —
        // ~24M comparisons a tick once a founder population had died back.
        (1..self.cells.len() as u32)
            .filter(|&id| self.cells[id as usize].is_alive())
            .collect()
    }

    /// Set the cell_id on a tile in the current grid (used by spawner).
    pub fn set_current_tile_cell_id(&mut self, x: u16, y: u16, cell_id: u32) {
        let idx = self.tile_index(x, y);
        self.grids[self.current][idx].cell_id = cell_id;
    }

    /// `(id, cell)` for every living cell, in pool order.
    pub fn live(&self) -> Vec<(u32, &Cell)> {
        (1..self.cells.len() as u32)
            .filter(|&id| self.cells[id as usize].is_alive())
            .map(|id| (id, &self.cells[id as usize]))
            .collect()
    }

    /// Consistency check between the grid and the pool: `(cells whose
    /// position field disagrees with the tile holding them, living cells on
    /// no tile at all)`. Both are 0 in a healthy world; B2 and B11 in the
    /// handover were each one of these.
    pub fn integrity(&self) -> (u32, u32) {
        let mut mismatch = 0;
        let mut on_tile = vec![false; self.cells.len()];
        for (i, tile) in self.grids[self.current].iter().enumerate() {
            if tile.cell_id != 0 {
                on_tile[tile.cell_id as usize] = true;
                let pos = (
                    (i % self.width as usize) as u16,
                    (i / self.width as usize) as u16,
                );
                if self.cells[tile.cell_id as usize].position != pos {
                    mismatch += 1;
                }
            }
        }
        let ghosts = (1..self.cells.len())
            .filter(|&i| self.cells[i].is_alive() && !on_tile[i])
            .count() as u32;
        (mismatch, ghosts)
    }

    /// Total number of live cells (excluding sentinel).
    pub fn population(&self) -> u32 {
        (self.cells.len() as u32 - 1) - self.free_list.len() as u32
    }
}

// ── Sunlight computation (Beer-Lambert column scan) ─────────────────

/// Recompute sunlight for the entire grid using Beer-Lambert attenuation.
/// For each column, light starts at 255 at the top and is attenuated row
/// by row based on each tile's absorption coefficient (α).
///
/// Called once at init and once per tick (after diffusion, before sensing).

// @veridikt
// purpose: "Compute per-tile sunlight by attenuating a top-down light column (Beer-Lambert): cells, decay, toxin and pheromone all cast shade below them"
// because: "Light comes from above and is consumed on the way down, so depth, crowding and pollution all reduce photosynthesis income — this creates the vertical light-vs-vent niche gradient"
/// Project one cell into the view the renderer sees.

// @veridikt
// purpose: "Summarize a cell for rendering: strategy class, how specialized it is, energy and age as fractions of its own limits, and its active phase"
// because: "The renderer must not decode genomes or know about config; a snapshot is a frozen projection the main thread can draw without touching the sim"
// depends_on: Genome.decode, Energy.storage_cap, Energy.lifespan_ticks
fn cell_view(cell: &Cell, config: &WorldConfig) -> CellView {
    use crate::sim::energy;

    let decoded = cell.genome.decode(config);
    let (strategy, specialization) = strategy_of(&decoded);

    let cap = energy::storage_cap(&decoded, config);
    let lifespan = energy::lifespan_ticks(&decoded, config).max(1);

    CellView {
        x: cell.position.0,
        y: cell.position.1,
        genome: cell.genome.hash(),
        strategy,
        specialization,
        energy_fraction: (cell.energy / cap).clamp(0.0, 1.0),
        age_fraction: (cell.age as f32 / lifespan as f32).clamp(0.0, 1.0),
        active_phase: cell.active_phase,
    }
}

/// The acquisition channel a genome is built around, and how dominant it is
/// over the runner-up (0.0-1.0). This is what the genes *allow*;
/// `CellRecord::diet` is what the cell has actually lived on.

// @veridikt
// purpose: "Classify decoded genes by their strongest acquisition channel, with a specialization score for the gap to the runner-up"
// because: "One definition shared by the renderer's strategy colours and the lab's census, so the window and the measurements cannot disagree about what a cell is"
pub fn strategy_of(decoded: &DecodedGenes) -> (Strategy, f32) {
    use crate::sim::genome as g;

    let channels = [
        (
            Strategy::Photosynthesis,
            decoded.get(g::PHOTOSYNTHESIS_RATE),
        ),
        (
            Strategy::Thermosynthesis,
            decoded.get(g::THERMOSYNTHESIS_RATE),
        ),
        (Strategy::Scavenging, decoded.get(g::SCAVENGE_ABILITY)),
        (Strategy::Predation, decoded.get(g::PREDATION_EFFICIENCY)),
    ];

    let mut best = (Strategy::None, 0.0_f32);
    let mut runner_up = 0.0_f32;
    for &(strategy, value) in &channels {
        if value > best.1 {
            runner_up = best.1;
            best = (strategy, value);
        } else if value > runner_up {
            runner_up = value;
        }
    }

    // Below this a cell has no working acquisition method worth showing.
    const EXPRESSED: f32 = 0.05;
    let strategy = if best.1 < EXPRESSED {
        Strategy::None
    } else {
        best.0
    };
    let specialization = if best.1 > 0.0 {
        ((best.1 - runner_up) / best.1).clamp(0.0, 1.0)
    } else {
        0.0
    };
    (strategy, specialization)
}

// @veridikt
// purpose: "Beer-Lambert column scan: light enters at y = 0 and each tile attenuates it by water depth, cells (cell_light_absorption), decay, toxin and pheromone"
// because: "An occupied tile shading the rows below is what makes depth a niche axis; the per-cell absorption is config so the photic band's depth can be tuned"
pub fn recompute_sunlight(
    grid: &mut [Tile],
    width: u32,
    height: u32,
    base_alpha: f32,
    cell_alpha: f32,
) {
    // Per-row base absorption from water depth alone
    let water_alpha = base_alpha / height as f32;
    // Most tiles are plain water, whose attenuation is the same constant
    // every time. `tile_absorption` adds exactly 0.0 for an empty tile with no
    // decay, toxin or pheromone, so reusing this value is bit-identical to
    // calling `exp` there — and `exp` on all 262 144 tiles was most of the
    // 22-31% of each tick this function cost.
    let water_attenuation = (-water_alpha).exp();

    // Row-major with one running intensity per column. Each column still
    // multiplies the same factors in the same top-to-bottom order, so every
    // value is unchanged; the old column-major walk strode `width` tiles per
    // step through the grid and missed cache on almost every access.
    let mut intensity = vec![255.0_f32; width as usize];
    for y in 0..height as usize {
        let row = &mut grid[y * width as usize..(y + 1) * width as usize];
        for (tile, light) in row.iter_mut().zip(intensity.iter_mut()) {
            // Write sunlight first (light arriving at this row), then
            // attenuate for the next row based on this tile's absorption.
            tile.sunlight = light.clamp(0.0, 255.0) as u8;

            let plain_water = tile.cell_id == 0
                && tile.decay_energy == 0.0
                && tile.toxin == 0.0
                && tile.pheromone == 0.0;
            *light *= if plain_water {
                water_attenuation
            } else {
                (-tile_absorption(tile, water_alpha, cell_alpha)).exp()
            };
        }
    }
}

fn tile_absorption(tile: &Tile, water_alpha: f32, cell_alpha: f32) -> f32 {
    let mut tile_alpha = water_alpha;
    if tile.cell_id != 0 {
        tile_alpha += cell_alpha;
    }
    tile_alpha += tile.decay_energy * 0.004 + tile.toxin * 0.002 + tile.pheromone * 0.001;
    tile_alpha
}

// ── Tests ───────────────────────────────────────────────────────────
#[cfg(test)]
mod tests {
    use super::*;
    use crate::sim::genome::{GENOME_LEN, Genome};

    fn small_config() -> WorldConfig {
        WorldConfig {
            grid_width: 16,
            grid_height: 16,
            vent_count: 2,
            initial_decay_matter: 0.0,
            ..WorldConfig::default()
        }
    }

    fn make_cell_at(x: u16, y: u16) -> Cell {
        Cell::new(Genome::new([0u8; GENOME_LEN]), 50.0, (x, y))
    }

    // ── Tile tests ──────────────────────────────────────────────────

    #[test]
    fn empty_tile_has_no_cell() {
        assert_eq!(Tile::EMPTY.cell_id, 0);
    }

    #[test]
    fn empty_tile_has_zero_environmental_state() {
        let t = Tile::EMPTY;
        assert!((t.decay_energy).abs() < f32::EPSILON);
        assert!((t.pheromone).abs() < f32::EPSILON);
        assert!((t.toxin).abs() < f32::EPSILON);
        assert_eq!(t.temperature, 0);
        assert_eq!(t.sunlight, 0);
    }

    #[test]
    fn tile_is_copy() {
        let a = Tile::EMPTY;
        let b = a;
        assert_eq!(a.cell_id, b.cell_id);
    }

    #[test]
    fn tile_size_reasonable() {
        let size = std::mem::size_of::<Tile>();
        assert!(
            size <= 24,
            "Tile is {size} bytes — expected ≤24 (target ~18)"
        );
    }

    // ── Toroidal wrapping ───────────────────────────────────────────

    #[test]
    fn wrap_normal_coordinates() {
        let w = World::new(&small_config());
        assert_eq!(w.wrap(5, 10), (5, 10));
    }

    #[test]
    fn wrap_negative_x() {
        let w = World::new(&small_config());
        assert_eq!(w.wrap(-1, 0), (15, 0)); // -1 mod 16 = 15
    }

    #[test]
    fn wrap_negative_y() {
        let w = World::new(&small_config());
        assert_eq!(w.wrap(0, -1), (0, 15));
    }

    #[test]
    fn wrap_overflow_x() {
        let w = World::new(&small_config());
        assert_eq!(w.wrap(16, 0), (0, 0)); // 16 mod 16 = 0
    }

    #[test]
    fn wrap_overflow_y() {
        let w = World::new(&small_config());
        assert_eq!(w.wrap(0, 17), (0, 1)); // 17 mod 16 = 1
    }

    #[test]
    fn wrap_large_negative() {
        let w = World::new(&small_config());
        assert_eq!(w.wrap(-33, -33), (15, 15)); // -33 mod 16 = 15
    }

    #[test]
    fn tile_index_matches_row_major() {
        let w = World::new(&small_config());
        assert_eq!(w.tile_index(0, 0), 0);
        assert_eq!(w.tile_index(1, 0), 1);
        assert_eq!(w.tile_index(0, 1), 16); // second row
        assert_eq!(w.tile_index(15, 15), 255); // last tile
    }

    // ── World init ──────────────────────────────────────────────────

    #[test]
    fn world_grid_dimensions() {
        let w = World::new(&small_config());
        assert_eq!(w.width, 16);
        assert_eq!(w.height, 16);
        assert_eq!(w.grids[0].len(), 256);
        assert_eq!(w.grids[1].len(), 256);
    }

    #[test]
    fn sunlight_gradient_top_brighter_than_bottom() {
        let w = World::new(&small_config());
        let top_sunlight = w.current_tile(0, 0).sunlight;
        let bottom_sunlight = w.current_tile(0, 15).sunlight;
        assert!(
            top_sunlight > bottom_sunlight,
            "top ({top_sunlight}) should be brighter than bottom ({bottom_sunlight})"
        );
    }

    #[test]
    fn sunlight_top_row_is_brightest() {
        let w = World::new(&small_config());
        let top = w.current_tile(0, 0).sunlight;
        // Top row receives light before any absorption, should be near max
        assert!(top >= 250, "top row should be near-max sunlight, got {top}");
    }

    #[test]
    fn sunlight_monotonically_decreases_with_depth() {
        let w = World::new(&small_config());
        for y in 1..16u16 {
            let above = w.current_tile(0, y - 1).sunlight;
            let here = w.current_tile(0, y).sunlight;
            assert!(
                here <= above,
                "row {y} ({here}) should not be brighter than row {} ({above})",
                y - 1
            );
        }
    }

    #[test]
    fn sunlight_affected_by_tile_contents() {
        let config = small_config();
        let mut w = World::new(&config);
        // Record baseline sunlight at bottom
        let baseline = w.current_tile(0, 15).sunlight;

        // Add toxin to several tiles in column 0
        for y in 0..8u32 {
            let idx = (y * config.grid_width) as usize;
            w.grids[w.current][idx].toxin = 50.0;
        }
        w.update_sunlight(
            config.sunlight_gradient_strength,
            config.cell_light_absorption,
        );

        let after_toxin = w.current_tile(0, 15).sunlight;
        assert!(
            after_toxin < baseline,
            "toxin should reduce sunlight: baseline={baseline}, after={after_toxin}"
        );
    }

    /// The light a cell takes from the column below it was a hard-coded 0.2
    /// in `tile_absorption`; it is `cell_light_absorption` now, so how deep a
    /// colony shades itself out can be tuned.
    #[test]
    fn a_cell_shades_the_tiles_below_it_by_the_configured_absorption() {
        let below = |alpha: f32| {
            let config = WorldConfig {
                cell_light_absorption: alpha,
                ..small_config()
            };
            let mut w = World::new(&config);
            for y in 0..4u16 {
                w.set_current_tile_cell_id(3, y, 1);
            }
            w.update_sunlight(config.sunlight_gradient_strength, alpha);
            w.current_tile(3, 4).sunlight
        };
        let (dense, thin) = (below(0.2), below(0.05));
        assert!(
            thin > dense + 50,
            "four cells at 0.05 left {thin}, at 0.2 {dense}: the knob should matter"
        );
    }

    #[test]
    fn a_fresh_world_carries_starting_detritus_for_scavengers() {
        // The scavenger niche does not exist until something dies: measured
        // `decay_current` 0.0 for the first ~70 ticks, with the first real
        // corpse wave 300+ ticks out and a scavenger's runway at 157 ticks.
        // Seeded detritus is what gives a tick-0 scavenger anything to eat.
        let config = WorldConfig {
            grid_width: 16,
            grid_height: 16,
            vent_count: 0,
            initial_decay_matter: 8.0,
            ..WorldConfig::default()
        };
        let world = World::new(&config);
        for y in 0..config.grid_height as u16 {
            for x in 0..config.grid_width as u16 {
                let tile = world.current_tile(x, y);
                assert!((tile.decay_energy - 8.0).abs() < f32::EPSILON);
                // ...and it fades at the world rate, not at 0 (immortal).
                assert!(tile.decay_fade > 0.0);
            }
        }
    }

    #[test]
    fn the_vent_zone_does_not_wrap_into_the_photic_rows() {
        // docs/spec.md, vertical resource axis: "Top zone: high sunlight,
        // no vents". The zone used to wrap in y, so a vent on the bottom
        // row also reached rows 0..vent_radius — the brightest rows, where
        // the Beer-Lambert column starts. Photosynthesizers standing there
        // divided every vent's output without drawing on it.
        let config = WorldConfig {
            grid_width: 64,
            grid_height: 64,
            vent_count: 1,
            vent_radius: 6,
            ..WorldConfig::default()
        };
        let world = World::new(&config);
        let vx = world.vent_positions[0] as u16;
        let bottom = (config.grid_height - 1) as u16;

        assert!(world.is_in_vent_zone(vx, bottom, config.vent_radius));
        assert!(world.is_in_vent_zone(vx, bottom - config.vent_radius as u16, config.vent_radius));
        assert!(!world.is_in_vent_zone(
            vx,
            bottom - config.vent_radius as u16 - 1,
            config.vent_radius
        ));
        // The rows just past the seam are the top of the light column.
        for y in 0..config.vent_radius as u16 {
            assert!(
                !world.is_in_vent_zone(vx, y, config.vent_radius),
                "row {y} is in the vent zone"
            );
        }
        // x still wraps: the bottom edge is a ring.
        let far_x = (vx as i32 - config.vent_radius as i32).rem_euclid(config.grid_width as i32);
        assert!(world.is_in_vent_zone(far_x as u16, bottom, config.vent_radius));
    }

    #[test]
    fn vent_positions_count() {
        let w = World::new(&small_config());
        assert_eq!(w.vent_positions.len(), 2);
    }

    // ── Cell pool ───────────────────────────────────────────────────

    #[test]
    fn spawn_returns_nonzero_id() {
        let mut w = World::new(&small_config());
        let id = w.spawn_cell(make_cell_at(1, 1));
        assert!(id > 0, "id 0 is reserved sentinel");
    }

    #[test]
    fn spawn_and_retrieve() {
        let mut w = World::new(&small_config());
        let id = w.spawn_cell(make_cell_at(3, 7));
        let cell = w.get_cell(id);
        assert_eq!(cell.position, (3, 7));
        assert!((cell.energy - 50.0).abs() < f32::EPSILON);
    }

    #[test]
    fn kill_and_reuse_slot() {
        let mut w = World::new(&small_config());
        let id1 = w.spawn_cell(make_cell_at(0, 0));
        w.kill_cell(id1);
        let id2 = w.spawn_cell(make_cell_at(5, 5));
        assert_eq!(id2, id1, "should reuse the freed slot");
        assert_eq!(w.get_cell(id2).position, (5, 5));
    }

    #[test]
    fn get_cell_mut_modifies_in_place() {
        let mut w = World::new(&small_config());
        let id = w.spawn_cell(make_cell_at(0, 0));
        w.get_cell_mut(id).energy = 999.0;
        assert!((w.get_cell(id).energy - 999.0).abs() < f32::EPSILON);
    }

    #[test]
    fn population_tracks_live_cells() {
        let mut w = World::new(&small_config());
        assert_eq!(w.population(), 0);
        let id1 = w.spawn_cell(make_cell_at(0, 0));
        let _id2 = w.spawn_cell(make_cell_at(1, 1));
        assert_eq!(w.population(), 2);
        w.kill_cell(id1);
        assert_eq!(w.population(), 1);
    }

    // ── Double buffering ────────────────────────────────────────────

    #[test]
    fn write_next_then_swap_reads_from_current() {
        let mut w = World::new(&small_config());
        // Write to next grid
        w.next_tile_mut(3, 3).decay_energy = 42.0;
        // Before swap: current grid should still be empty
        assert!((w.current_tile(3, 3).decay_energy).abs() < f32::EPSILON);
        // After swap: the written data is now in current
        w.swap_buffers();
        assert!((w.current_tile(3, 3).decay_energy - 42.0).abs() < f32::EPSILON);
    }

    #[test]
    fn prepare_next_carries_environment_and_clears_cells() {
        let mut w = World::new(&small_config());
        w.update_sunlight(0.1, 0.2);
        let idx = w.tile_index(5, 5);
        let t = &mut w.current_grid_mut()[idx];
        t.decay_energy = 30.0;
        t.pheromone = 7.0;
        t.toxin = 3.0;
        t.cell_id = 9;
        // Stale state left in next from two ticks ago must not survive.
        w.next_tile_mut(6, 6).decay_energy = 100.0;
        w.next_tile_mut(6, 6).cell_id = 42;

        w.prepare_next();

        for y in 0..16 {
            for x in 0..16 {
                let (c, n) = (*w.current_tile(x, y), *w.next_tile(x, y));
                assert_eq!(n.cell_id, 0);
                assert_eq!(n.sunlight, c.sunlight);
                assert_eq!(n.temperature, c.temperature);
                assert_eq!(n.decay_energy, c.decay_energy);
                assert_eq!(n.pheromone, c.pheromone);
                assert_eq!(n.toxin, c.toxin);
            }
        }
        assert_eq!(w.next_tile(5, 5).decay_energy, 30.0);
        assert!(w.next_tile(0, 0).sunlight > 0);
    }

    // ── Spatial query ───────────────────────────────────────────────

    #[test]
    fn neighbors_radius_zero_returns_nothing() {
        let w = World::new(&small_config());
        let result = w.neighbors_in_radius(5, 5, 0);
        assert!(result.is_empty());
    }

    #[test]
    fn neighbors_finds_adjacent_cell() {
        let mut w = World::new(&small_config());
        let id = w.spawn_cell(make_cell_at(6, 5));
        // Place the cell on the current grid
        let idx = w.tile_index(6, 5);
        w.grids[w.current][idx].cell_id = id;

        let result = w.neighbors_in_radius(5, 5, 1);
        assert_eq!(result.len(), 1);
        assert_eq!(result[0], (6, 5, id));
    }

    #[test]
    fn neighbors_wraps_at_edge() {
        let mut w = World::new(&small_config());
        // Place a cell at (15, 0) — right edge
        let id = w.spawn_cell(make_cell_at(15, 0));
        let idx = w.tile_index(15, 0);
        w.grids[w.current][idx].cell_id = id;

        // Search from (0, 0) with radius 1 — should wrap and find (15, 0)
        let result = w.neighbors_in_radius(0, 0, 1);
        assert!(
            result.iter().any(|&(x, y, _)| x == 15 && y == 0),
            "should find cell at (15,0) via toroidal wrap"
        );
    }

    #[test]
    fn neighbors_radius_3_covers_expected_area() {
        let w = World::new(&small_config());
        // No cells placed, but verify the scan covers the right number of tiles
        // Radius 3 = 7x7 grid minus center = 48 tiles scanned
        let result = w.neighbors_in_radius(8, 8, 3);
        assert!(result.is_empty()); // no cells, but no crash
    }

    // ── Snapshot ────────────────────────────────────────────────────

    #[test]
    fn snapshot_reflects_current_state() {
        let mut w = World::new(&small_config());
        let id = w.spawn_cell(make_cell_at(2, 3));
        let idx = w.tile_index(2, 3);
        w.grids[w.current][idx].cell_id = id;
        w.grids[w.current][idx].decay_energy = 7.5;
        w.tick = 42;

        let snap = w.snapshot(&small_config());
        assert_eq!(snap.tick, 42);
        assert_eq!(snap.cells.len(), 1);
        assert_eq!(snap.cells[0].x, 2);
        assert_eq!(snap.cells[0].y, 3);
        assert_eq!(snap.stats.population, 1);
        assert!((snap.decay_map[idx] - 7.5).abs() < f32::EPSILON);
    }

    #[test]
    fn snapshot_carries_what_the_renderer_needs() {
        // The snapshot used to be (x, y, hash), so no view could show a
        // phase, a strategy or a starving cell.
        use crate::sim::genome::{self, GENOME_LEN, Genome};

        let config = small_config();
        let mut w = World::new(&config);
        let mut data = [10u8; GENOME_LEN];
        data[genome::PHOTOSYNTHESIS_RATE] = 255;
        let mut cell = Cell::new(Genome::new(data), 30.0, (4, 4));
        cell.active_phase = 2;
        cell.age = 100;
        let id = w.spawn_cell(cell);
        let idx = w.tile_index(4, 4);
        w.grids[w.current][idx].cell_id = id;

        let view = w.snapshot(&config).cells[0];
        assert_eq!(view.strategy, Strategy::Photosynthesis);
        assert_eq!(view.active_phase, 2);
        assert!(
            view.specialization > 0.5,
            "a pure photo cell is specialized"
        );
        assert!(
            view.energy_fraction > 0.0 && view.energy_fraction < 1.0,
            "energy fraction {} should be a real share of the cap",
            view.energy_fraction
        );
        assert!(view.age_fraction > 0.0);
    }

    #[test]
    fn snapshot_classifies_an_unexpressed_genome_as_none() {
        use crate::sim::genome::{GENOME_LEN, Genome};

        let config = small_config();
        let mut w = World::new(&config);
        let id = w.spawn_cell(Cell::new(Genome::new([0u8; GENOME_LEN]), 10.0, (1, 1)));
        let idx = w.tile_index(1, 1);
        w.grids[w.current][idx].cell_id = id;

        assert_eq!(w.snapshot(&config).cells[0].strategy, Strategy::None);
    }

    // ── Grid accessors ──────────────────────────────────────────────

    #[test]
    fn next_grid_accessible() {
        let config = small_config();
        let world = World::new(&config);
        let total = (config.grid_width * config.grid_height) as usize;
        assert_eq!(world.next_grid().len(), total);
    }

    #[test]
    fn cell_ids_returns_live_cells() {
        let config = small_config();
        let mut world = World::new(&config);
        let genome = Genome::new([50u8; GENOME_LEN]);
        let cell = Cell::new(genome, 100.0, (3, 3));
        let id = world.spawn_cell(cell);
        // cell_ids should include the spawned cell
        let ids = world.cell_ids();
        assert!(ids.contains(&id));
        // kill it — should no longer appear
        world.kill_cell(id);
        let ids = world.cell_ids();
        assert!(!ids.contains(&id));
    }
}
